CREATE DATABASE forestal


--TABLA TIPO EMPLEADO
--TABLA EMPLEADO
--TABLA ANTICIPO

--TABLA SUPERMERCADO
--TABLA VALE
--TABLA INSUMO

--TABLA EMPLEADO INSUMO 
--TABLA REMITO
--TABLA EMPLEADO REMITO

--TABLA CORTE
--TABLA PRODUCCIONES
--TABLA PRODUCCIONES CORTE
--TABLA EMPLEADO PRODUCCIONES
