CREATE DATABASE forestal


--TABLA TIPO_EMPLEADO
--TABLA EMPLEADO
--TABLA ANTICIPO
--TABLA SUPERMERCADO

--TABLA VALE
--TABLA INSUMO
--TABLA EMPLEADO_INSUMO 
--TABLA REMITO
--TABLA EMPLEADO REMITO

--TABLA CORTE
--TABLA PRODUCCIONES
--TABLA PRODUCCIONES_CORTE
--TABLA EMPLEADO_PRODUCCIONES
